# Generated by Django 6.0.2 on 2026-02-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('kc_min', models.DecimalField(decimal_places=3, max_digits=5)),
                ('kc_max', models.DecimalField(decimal_places=3, max_digits=5)),
                ('root_depth_min_m', models.DecimalField(decimal_places=2, max_digits=4)),
                ('root_depth_max_m', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
