# Generated by Django 6.0.2 on 2026-02-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('theta_fc_min', models.DecimalField(decimal_places=3, max_digits=5)),
                ('theta_fc_max', models.DecimalField(decimal_places=3, max_digits=5)),
                ('theta_wp_min', models.DecimalField(decimal_places=3, max_digits=5)),
                ('theta_wp_max', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
