# Generated by Django 6.0.2 on 2026-02-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_soiltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='p',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
            preserve_default=False,
        ),
    ]
