# Generated by Django 6.0.2 on 2026-02-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ET0Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('et0_mm', models.FloatField()),
                ('source', models.CharField(default='open-meteo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.field')),
            ],
        ),
    ]
