# Generated by Django 6.0.2 on 2026-02-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_et0daily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
