# Generated by Django 6.0.1 on 2026-02-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_longtitude_field_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='p',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='root_depth_max_m',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='root_depth_min_m',
        ),
        migrations.AddField(
            model_name='crop',
            name='kc_default',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
