# Generated by Django 6.0.1 on 2026-03-05 12:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_crop_p_remove_crop_root_depth_max_m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='kc_default',
        ),
        migrations.AddField(
            model_name='crop',
            name='p',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='root_depth_max_m',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='root_depth_min_m',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.crop'),
        ),
        migrations.AddField(
            model_name='field',
            name='p_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='root_depth_override_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.soiltype'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_max',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='crop',
            name='kc_min',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
