# Generated by Django 6.0.1 on 2026-03-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_crop_kc_default_crop_p_crop_root_depth_max_m_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='et0daily',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='et0daily',
            name='rain_mm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='et0daily',
            unique_together={('field', 'date')},
        ),
    ]
