# Generated by Django 6.0.1 on 2026-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_et0daily_options_et0daily_rain_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='kc_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='kc_ini',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='kc_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
