# Generated by Django 6.0.1 on 2026-03-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_crop_kc_end_crop_kc_ini_crop_kc_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='stage_dev_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='stage_ini_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='stage_late_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='stage_mid_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
