# Generated by Django 6.0.1 on 2026-03-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_crop_stage_dev_days_crop_stage_ini_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='sowing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
