# Generated by Django 6.0.1 on 2026-03-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_field_sowing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='kc_max',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='kc_min',
        ),
    ]
