# Generated by Django 6.0.1 on 2026-03-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_crop_kc_max_remove_crop_kc_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoistureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('output_type', models.CharField(choices=[('analog_mv', 'Analóg mV'), ('analog_v', 'Analóg V'), ('api', 'API/platforma'), ('manual', 'Ručný vstup')], default='manual', max_length=20)),
                ('installation_depth_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_sensors', to='catalog.field')),
            ],
        ),
    ]
