# Generated by Django 6.0.1 on 2026-03-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_soilmoisturesensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoistureMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('vwc_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='catalog.soilmoisturesensor')),
            ],
            options={
                'ordering': ('-measured_at',),
            },
        ),
    ]
