# Generated by Django 6.0.1 on 2026-03-13 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_soilmoisturemeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilmoisturemeasurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
